### ISSUE TITLE
Assets undefined

### ISSUE THREAD

**Issue by esetnik** [techpines/asset-rack#10]
`!= assets.tag('/app.js') assets is not defined` is shown in the browser
# Setup

```
var assets = new rack.AssetRack([
    new rack.BrowserifyAsset({
        url: '/app.js',
        filename: __dirname + '/public/javascripts/app.js'
    }),
    new rack.JadeAsset({
        url: '/templates.js',
        dirname: __dirname + '/views'
    })
]);

assets.on('complete', function() {
    logger.info("static asset compilation complete");
    app.use(assets);  // that's all you need to do
});
```

**Comment by techpines** [comment]
Here I just setup a similar project, and I was able to get it working.

Try this code, and make sure that you have an "index.jade" script in your views folder.

``` javascript
express = require('express');
rack = require('asset-rack');

var assets = new rack.AssetRack([
    new rack.BrowserifyAsset({
        url: '/app.js',
        filename: __dirname + '/public/javascript/app.js'
    }),
    new rack.JadeAsset({
        url: '/templates.js',
        dirname: __dirname + '/views'
    })
]);

assets.on('complete', function() {
    app = express();
    app.configure(function() {
        app.set('views', __dirname + "/views");
        app.set('view engine', 'jade');
        app.use(assets);  // that's all you need to do
    });
    app.get('/', function(req, res) {
        res.render('index');
    });
    app.listen(8000);
});

```

**Comment by techpines** [comment]
Here is what my "views/index.jade" page looked like to make it a little clearer:

```

!!! 5
html
  head
    != assets.tag('/app.js')
    != assets.tag('/templates.js')
  body
    h1 Hellow World
```

**Comment by esetnik** [comment]
What express version are you using?

**Comment by techpines** [comment]
I am using express, 3.0.0rc4 and node 0.8.4.  Also, below is a link to my test package. You can run the following bash code to pull it down and run it.

Test Package: https://s3.amazonaws.com/temp.techpines.com/test.tar.gz

``` bash
curl -O https://s3.amazonaws.com/temp.techpines.com/test.tar.gz
tar -xzf test.tar.gz
cd test
node app.js
```

**Comment by ritchiey** [comment]
I had a similar problem so this thread was really useful. Brad's code pasted above was working so I knew it must be my code rather than version numbers and sure enough, it was the order that the middleware modules were being loaded.

The app.use(assets) has to appear before the app.use(app.router) or assets won't be available in the templates.

**Comment by brentjanderson** [comment]
This thread helped me as well, and ritchiey's fix worked for me too: app.use(assets) has to come before app.use(app.router)

**Comment by techpines** [comment]
I added a note about this in the docs.
