### ISSUE TITLE
Stylus compiler fails miserably

### ISSUE THREAD

**Issue by max-degterev** [techpines/asset-rack#24]
```
11 Feb 19:19:00 - [nodemon] starting `node app.js`

/Users/Max/Projects/mobota/node_modules/asset-rack/lib/asset.coffee:85
          throw error;
                ^
TypeError: /Users/Max/Projects/mobota/public/css/app.styl:5
   1| // @import './mixin'
   2| 
   3| body
   4|   background: #000
 > 5| 

Cannot read property 'length' of null
```

It looks like .render (error, css) => always throws an error. Hem from spinejs works with stylus fine though, so def not stylus problem

**Comment by techpines** [comment]
:(   

There was an issues with asset dependencies in the less module, and I added a similar fix and a test for stylus.

```
asset-rack@2.0.4
```

Give 2.0.4 a try, and if it doesn't work you might have to put up your stylus code so I can test it to figure out what the problem is.

Here's where the current stylus tests are:

```
test/stylus.coffee
test/fixtures/stylus
```

**Comment by max-degterev** [comment]
Stylus works OK, however starting with version 2 snockets fails :(

**Comment by techpines** [comment]
Sweet.

Can you give an example of the Snockets issue?

**Comment by max-degterev** [comment]
Ooops looks like missing matching curly brace at the end of output css file

```
html,
body,
#l-screens,
#l-slider {
  width: 100%;
  height: 100%;
  overflow: hidden;
}
.l-slide {
  min-height: 100%;
}
.l-sidebar {
  display: none;
  background: #181a1c;
```

**Comment by techpines** [comment]
This seems like the same issue with snockets.  I think it's related to the Content-Length not being set correctly.

Give asset-rack@2.0.6 a try.

**Comment by max-degterev** [comment]
Indeed! Thanks!
