### ISSUE TITLE
hashed url for stylus assets doesn't work

### ISSUE THREAD

**Issue by troygoode** [techpines/asset-rack#26]
I can access the output of my stylus file just fine if I navigate to /css/app.css, but if I use assets.tag or assets.url, it won't work (I get `Cannot GET /css/app-a8c4e5f26745712564df2a8a9f6e1bf5.css`).

**Comment by techpines** [comment]
It should be working.  What version of asset-rack/node.js are you running?

Also, can you throw up a little code?

The stylus tests and fixtures that I have currently are here:

```
test/stylus.coffee
test/fixtures/stylus
```

**Comment by troygoode** [comment]
Here is a repro:

https://github.com/TroyGoode/asset-rack-issue-26

After playing around quite a bit I've deduced that this problem appears only when dealing with mounted sub-apps (http://expressjs.com/api.html#app.use).

**Comment by troygoode** [comment]
For the time being I'm doing this instead:

`link(rel='stylesheet', href='/example#{assets.url('/css/app.css')}')`

Ughly, but works...

**Comment by techpines** [comment]
So when you do this:

```
app.use('/example', exampleApp);
```

The `exampleApp` here doesn't know what url prefix it is being served from.  Which is fine for a lot of applications, but this causes a problem because you need to send a full url back to the browser (not a partial one). 

Another solution, that might make the templates a little cleaner is this:

``` js
var assets = new rack.Rack([
  new rack.StylusAsset({
    url: '/example/css/app.css',
    filename: __dirname + '/public/css/app.styl'
  })
]);
```

And then reference it in the template:

```
!= assets.tag('/example/css/app.css')
```

**Comment by techpines** [comment]
Based on how express middleware works,  I don't think this is solvable in a completely transparent way.  I don't think there is any way to get it to work without telling the `exampleApp` explicitly that it's url prefix is "/example".

One idea I did have would be this:

``` js
var assets = new rack.Rack(assets, options);
```

Where one of the options is `urlPrefix`, and everything you did would work the same, except that your rack declaration would look like this:

``` js
var options = {urlPrefix: '/example'};

var assets = new rack.Rack([
  new rack.StylusAsset({
    url: '/css/app.css',
    filename: __dirname + '/public/css/app.styl'
  })
], options);
```

Let me know if you think that is a good solution, and I'll look to implement it.

Cheers.

**Comment by troygoode** [comment]
Setting a urlPrefix option would be fine for me.
