### ISSUE TITLE
stylus asset doesn't support compression

### ISSUE THREAD

**Issue by troygoode** [techpines/asset-rack#27]

**Comment by techpines** [comment]
Gzip compression, or removal of whitespace?  Or both?

**Comment by troygoode** [comment]
Preferably both, but I guess I actually was referring to minimization here rather than compression. I'm @importing bootstrap.css and it is blowing up the size of my file. I _could_ @import bootstrap.min.css, but I prefer to just keep the full version around for debugging purposes and let it get compressed at runtime (ideally only when NODE_ENV is 'production').

**Comment by techpines** [comment]
This is already supported, I just forgot to put it in the docs.

``` js
app.use(new rack.StylusAsset({
  filename: __dirname + "/simple.styl",
  url: '/style.css',
  compress: true
})
```

**Comment by troygoode** [comment]
Ah nice, thanks!
