### ISSUE TITLE
Convert all files types of a given extension

### ISSUE THREAD

**Issue by drozzy** [techpines/asset-rack#38]
Do you guys have the capability for something like "If you see a file with extension *.foo - automatically serve it at the url as the file with extension *.bar"? 

Before I start writing my own junk I thought I'd ask you.

**Comment by techpines** [comment]
I'm guessing you're thinking about doing this *.ls to *.js recursively in a directory.

Yea, some of the other built-in assets do similar, but there is no standard fs walk tool yet.

But it sounds cool, so let me know how it goes.

**Comment by drozzy** [comment]
What about having some kind of asset that is similar to `StaticAssets` - but that will work for ... dynamic assets as well? So it would take a directory, and an asset "factory".

So, for example, I could use it to extend the functionality of my own (yes livescript :-) asset as:

```
new rack.DynamicAssets(LiveScriptAsset, {      
    urlPrefix: '/scripts'
    dirname: __dirname + '/ls'
}),
```

And it would do the same thing `StaticAssets` does but instead of creating an [Asset](https://github.com/techpines/asset-rack/blob/master/lib/modules/static.coffee#L36) for each file, it would create a LiveScriptAsset.

Anyways, ignore it if it sounds like gibberish.

**Comment by techpines** [comment]
That sounds awesome!

Except I think the syntax would need to look like this so that it wouldn't be breaking.

``` js
new rack.DynamicAssets({      
    type: LiveScriptAsset, 
    urlPrefix: '/scripts'
    dirname: __dirname + '/ls'
})
```

**Comment by drozzy** [comment]
I'm not an expert in coffeescript, could you tell me what the last two lines here do:
https://github.com/techpines/asset-rack/blob/master/lib/modules/static.coffee#L47

E.g. which function is this error handling function a parameter of?:

```
, (error) ->
        next()
```

**Comment by techpines** [comment]
For the CS, that's an error handling function for `async.forEachSeries`,(which looks like it's just `eachSeries` in newer versions).  Honestly, I think that code is a little too complex and should be refactored to use nodejs wrench.

I would look at these libraries to do what you're trying to do:

For recursing:
https://github.com/ryanmcgrath/wrench-js

For aync looping:
https://github.com/caolan/async#eachseriesarr-iterator-callback

For manipulating paths:
http://nodejs.org/api/path.html

**Comment by noc7c9** [comment]
Is there anyone working on a DynamicAssets class? If not I'm interested in making it myself.
I'm thinking that this should support any asset that takes a url and filename, right?
Meaning every builtin asset other than 
- the two template assets, JadeAsset and AngularTemplateAsset which both take a url and a dirname
- and StaticAssets (maybe StaticAssets should be reimplemented to use DynamicAssets to keep things DRY?)

eg:

``` coffee
new DynamicAssets
  type: StylusAsset
  urlPrefix: '/css'
  dirname: __dirname + '/styl'
  options:
    compress: true
```

Note: the options hash is passed directly to the StylusAsset constructor

**Comment by drozzy** [comment]
@noc7c9 Good idea, I was also thinking of merging them both together. Unfortunately I don't have the necessary chops to fork this repo and submit the change - so by all means go ahead!

I am not sure how generic you can make it, as in my case (for livescript) I had to get pretty specific:
https://github.com/drozzy/asset-rack-livescript/blob/master/livescript-asset.ls

With the `type` - user still has to write a custom class (e.g. StylusAsset in your case), and one might argue that those custom classes should be in the framework already... On the other hand, having a "DynamicAsset" class will make it easier for library writers to write new types of assets easier (which, in turn, will be used by users - and possibly integrated into rack).

**Comment by noc7c9** [comment]
StylusAsset is a builtin asset, and your LiveScriptAsset class will also work with DynamicAssets as I plan to make it.

The only requirement would be that the asset takes a url and filename as input.
Basically as long as you normally use an asset as below; it should work.

``` js
new CustomAssetClass({
  url: '/blah',  // this should be present
  filename: '/path/to/file'  // this too
});
```

Of course I have to make it first. :grinning:
I'll get on it as soon as I can.

**Comment by noc7c9** [comment]
@drozzy also you're correct in saying that these custom classes should be in the framework already, and it should be simple to add them. We can just build these classes on top of Dynamic Assets
Something like this?

``` coffee
class StylusAssets extend DynamicAssets
  constructor: (options) ->
    options.type = StylusAsset
    super options
```

...and done! Now we have `StylusAsset` to serve a single stylus file and `StylusAssets` (note the plurality) to serve an entire folder of stylus files.
This is also how I plan to reimplement StaticAssets.

We can make a similar class for each other builtin asset as well, though the names might have to be changed since a difference of a single letter could can cause hard to notice typos.

**Comment by noc7c9** [comment]
@drozzy maybe you should think about adding that LiveScriptAsset class to asset-rack; would get better use if it were a builtin asset.
Just convert it to coffeescript first.

**Comment by noc7c9** [comment]
@techpines should I implement this using wrench-js? or would you rather not have another dependency?
I don't mind either way.

**Comment by techpines** [comment]
Yea, wrench is totally fine.  

It would be great if whatever recursive code you use could be wrapped in a `utils` module.  A few people have found it complex to build assets based on directories, and there are probably some other utility functions that would make custom assets easier to build.  

```
rack.utils.readdirSyncRecursive(dirname)
```

**Comment by drozzy** [comment]
@techpines My pet peeve is with anything named "utils" - it says nothing about the purpose of the code inside of it.
Sorry :)

@noc7c9 Maybe I'll convert it once dynamic asset is available. Note that keeping it separate imo also forces modularization of asset-rack itself.

**Comment by techpines** [comment]
@drozzy isn't that the point of `utils`?  you can't think of anything better. :) 

What would make more sense for a bunch of utility functions for building assets?

**Comment by drozzy** [comment]
I can try a few: `rack.dir`, `rack.recursive`, `rack.asset-factory`, `rack.builder`, `rack.scanning`, `rack.monitoring`, `rack.files`... I mean if you can't give it a name, how do you know what it's supposed to do in the first place? Which other things can and cannot go into utils in the future...

Again! Sorry for diverging the topic. Like I said... it's just my pet peeve hahaha.
