### ISSUE TITLE
modularisation

### ISSUE THREAD

**Issue by timoxley** [techpines/asset-rack#5]
#2, #3 and #4 could be achieved with external plugins similarly to the way grunt works, just need to provide instructions (also consider just using something like consolidate, https://github.com/visionmedia/consolidate.js for the template engine support).

You may even want to consider enabling this whole module as a grunt plugin itself… that would be cool

**Comment by techpines** [comment]
@timoxley thanks for the heads up on consolidate.js.  That looks like a really great way to add support for a lot of template engines very quickly.

As far as grunt goes, that looks interesting.  Do you have a link to how they do their plugins?

**Comment by timoxley** [comment]
I just learned from example, e.g. https://github.com/timoxley/grunt-ember or https://github.com/cowboy/grunt/tree/master/tasks
