### ISSUE TITLE
Problem (typo?) in less.coffee

### ISSUE THREAD

**Issue by chad-skidmore** [techpines/asset-rack#6]
Trying asset-rack this evening and ran into the error below. Looks like a likely typo in the less.coffee file. I edited to @trigger rather than @tigger but that fails as well. 

events.js:48
        throw arguments[1]; // Unhandled 'error' event
                       ^
TypeError: Object #<LessAsset> has no method 'tigger'
    at /Volumes/SATA/Development/projects/quotes/back/node_modules/asset-rack/lib/assets/less.coffee:40:26
    at Object.parse (/Volumes/SATA/Development/projects/quotes/back/node_modules/asset-rack/node_modules/less/lib/less/parser.js:343:24)
    at LessAsset.create (/Volumes/SATA/Development/projects/quotes/back/node_modules/asset-rack/lib/assets/less.coffee:38:23)
    at /Volumes/SATA/Development/projects/quotes/back/node_modules/asset-rack/lib/index.coffee:57:24
    at /Volumes/SATA/Development/projects/quotes/back/node_modules/async/lib/async.js:86:13
    at Array.forEach (native)
    at /Volumes/SATA/Development/projects/quotes/back/node_modules/async/lib/async.js:26:24
    at Object.forEach (/Volumes/SATA/Development/projects/quotes/back/node_modules/async/lib/async.js:85:9)
    at Array.0 (/Volumes/SATA/Development/projects/quotes/back/node_modules/asset-rack/lib/index.coffee:53:22)
    at EventEmitter._tickCallback (node.js:190:38)

**Comment by techpines** [comment]
@chad-skidmore it's not well documented but you can catch errors like this,

``` javascript
// wait for assets to complete
assets.on('complete', function() {console.log('hey my assets are ready')});

// handle errors
assets.on('error', function(error) {console.log(error)});
```

So, it's probably an issue with your less, and if I had to guess it may be a problem with not specifying a search path for relative imports.

The less asset can accept a `paths` option, which is an array of paths to search for relative imports.  This is a result of how less works unfortunately.

Let me know if that doesn't fix it.

**Comment by techpines** [comment]
You have a less problem, but you are right that there is an issue with the code.  The reason the error is not propagating correctly is because `@trigger` should actually be `@emit`.  

I'll fix that and republish.

**Comment by techpines** [comment]
Ok, I republished.  Let me know if you have anymore issues otherwise I will close this issue out.

**Comment by chad-skidmore** [comment]
Thanks for the quick response. To much working with node events so I was thinking trigger rather than emit. It was a problem with my less path. I missed that it was a list rather than a single path so an easy fix. I also have my node code heavily modularized so it took some experimentation to insure that I was making the calls in express in the proper order. Working well now, thanks!

**Comment by techpines** [comment]
Glad to hear!
