### ISSUE TITLE
Add support for stylus

### ISSUE THREAD

**Issue by troygoode** [techpines/asset-rack#7]
Needed for connect-assets parity:

http://learnboost.github.com/stylus/

**Comment by techpines** [comment]
Sure, I will look to add this when I get some time.

**Comment by max-degterev** [comment]
Pretty please someone add stylus! My brain hurts when I switch from coffee & jade to less!

**Comment by techpines** [comment]
@suprMax This is coming in the next few days!

I've got a 2.x release for asset-rack, that is gonna be really badass!

I am just finishing up the docs.  And Stylus support will be in there!

**Comment by techpines** [comment]
Done!

**Comment by troygoode** [comment]
:joy: I'm super excited about this. Thanks!

**Comment by max-degterev** [comment]
Brings tear to my eye! And just in time for a new project! Thank you fine sir!
