### ISSUE TITLE
Can't get assets.url to show hash value

### ISSUE THREAD

**Issue by dankohn** [techpines/asset-rack#78]
I know I have asset-rack installed correctly, because both https://localhost:4000/hello.txt and https://localhost:4000/hello-5eb63bbbe01eeed093cb22bb8f5acdc3.txt return "hello world". However, in my app.js below app.use(assets) I have `console.log(assets.url('/hello.txt'))` which results in `undefined`.

Could you please point me to some examples of using assets.url. I'm not able to replicate any of the examples in your tests https://github.com/techpines/asset-rack/search?q=assets.url&ref=cmdform and get assets.url to report back the hashed URL.

Thanks.

**Comment by techpines** [comment]
The assets are compiled asynchronously, even a simple asset like your "hello" example does not execute until the next tick.

Try this:

``` js
app.use(assets);
assets.on('complete', function() {
    console.log(assets.url('/hello.txt'));
});
```

**Comment by dankohn** [comment]
Wow, that was a ludicrously fast response time, and completely fixed my issue. Thanks!
